# Generated by Django 5.0.6 on 2024-05-20 10:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0036_alter_gen_dt_contract_ourcompany_and_more'),
        ('docs', '0003_remove_doc_citizenship_doc_date_of_preparing_and_more'),
        ('employees', '0013_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doc',
            name='date_of_expiry',
        ),
        migrations.RemoveField(
            model_name='doc',
            name='date_of_preparing',
        ),
        migrations.AlterField(
            model_name='doc',
            name='address',
            field=models.TextField(blank=True, verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='current_status',
            field=models.CharField(choices=[('active', 'Faol'), ('inactive', 'Faol emas')], default='active', max_length=10, verbose_name='Holati'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='date_of_issue',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Berilgan sana'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='doc_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.documenttype', verbose_name='Hujjat turi'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee', verbose_name='Xodim'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='issued_authority',
            field=models.CharField(max_length=200, verbose_name='Kim tomonidan berilgan'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='number',
            field=models.CharField(max_length=200, verbose_name='Nomer №'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='others',
            field=models.TextField(blank=True, verbose_name="Qo'shimcha ma'lumotlar"),
        ),
        migrations.AlterField(
            model_name='doc',
            name='scanned_doc',
            field=models.FileField(blank=True, upload_to='docs/uploads/', verbose_name='Fayl yuklash'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='serial',
            field=models.CharField(max_length=200, verbose_name='Seriya'),
        ),
    ]
