# Generated by Django 4.1.5 on 2024-02-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_alter_employee_date_of_dismissal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_of_dismissal',
            field=models.DateField(blank=True, verbose_name='Дата увольнение'),
        ),
    ]
