# Generated by Django 5.0.6 on 2024-05-20 09:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0036_alter_gen_dt_contract_ourcompany_and_more'),
        ('employees', '0012_alter_employee_date_of_dismissal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['surname', 'firstname', 'other_name']},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='personnel_number',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='snils_number',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='tin_number',
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.TextField(blank=True, verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='citizenship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.citizenship', verbose_name='Fuqarolik'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='current_doc_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.permitdoccategory', verbose_name='Hujjat toifasi'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='current_status',
            field=models.CharField(choices=[('active', 'Ishlaydi'), ('inactive', 'Amaliyotchi')], default='active', max_length=10, verbose_name='Holati'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now, verbose_name="Tug'ilgan yili"),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_dismissal',
            field=models.DateField(blank=True, null=True, verbose_name='Shartnoma vaqti'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_employment',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Qabul qilingan sana'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='firstname',
            field=models.CharField(max_length=200, verbose_name='Ism'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('male', 'Erkak'), ('female', 'Ayol')], default='male', max_length=10, verbose_name='Jins'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='other_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Otasining ismi'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='others',
            field=models.TextField(blank=True, verbose_name="Qo'shimcha ma'lumotlar"),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, upload_to='employees/photos/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(max_length=200, verbose_name='Lavozim'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='surname',
            field=models.CharField(max_length=200, verbose_name='Familiya'),
        ),
    ]
