# Generated by Django 5.0.6 on 2024-05-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_remove_employee_current_doc_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefon raqami'),
        ),
    ]
